apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: game-2048
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: game-2048
            port:
              number: 8080