apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-2048
spec:
  replicas: 1
  selector:
    matchLabels:
      app: game-2048
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: game-2048
    spec:
      nodeSelector: 
        node-role.kubernetes.io/ingress : "true" # 인그레스 노드(Taint 설정있음)에 배포되게 설정
      # tolerations:
      # - effect: NoExecute
      #   key: node-role.dkosv3.9rum.cc/lb
      #   operator: Equal
      #   value: "true"
      containers:
        - name: backend
          # Replace with your docker registry info
          image: krmp-d2hub-idock.9rum.cc/dev-test/repo_b9f868837c50:latest
          ports:
            - name: http
              containerPort: 8080
          resources:
            requests:
              cpu: 200m
              memory: 100Mi
            limits:
              cpu: 300m
              memory: 200Mi
---
apiVersion: v1
kind: Service
metadata:
  name: game-2048
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: game-2048

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: game-2048
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: game-2048
            port:
              number: 8080